# Dependencies
markdown:           kramdown
pygments:           true

# Permalinks
permalink:          pretty

# Server
host:               172.0.0.1
port:               8080
baseurl:            /
url:                http://localhost:8080
encoding:           UTF-8

# the excluded directoies
exclude:            []

# site information
info:
  site_name:        MobDevGroup

# site.url, site.title

title: 'MobDevGroup'

## note:
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)

path: 'http://www.mobdevgroup.com'
url:  'http://www.mobdevgroup.com'

meta:
  description:      "移动开发在线分享"
  keywords:         "开发工具、Android、iOS、HTML5、设计、项目管理"
  author:           "yuxingxin"

# multiple language
language_default:   'cn'

languages:          ["en", "cn"]

# left navigation
left_nav:
  en:
    title:          MobDevGroup
    path:           /
    items:
      - path:       /page1
        title:      "Another page"
      - path:       /page2
        title:      "Yet another page"
  cn:
    title:          "MobDevGroup"
    path:           /cn
    items:
      - path:       /cn/page1
        title:      "页面1"
      - path:       /cn/page2
        title:      "页面2"

# right navigation
right_nav:
  - title:          English Version
    url:            /
  - title:          MobDevGroup
    url:            /cn
  - title:          Fork on Github
    url:            https://github.com/mobdevgroup

# analytics account information, remember to change this.
analytics:
  google:
    account:         
